services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  flyway:
    image: flyway/flyway:9
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    environment:
      FLYWAY_URL: ${DB_URL}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate

  maven:
    image: maven:3.9.4-eclipse-temurin-17
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      flyway:
        condition: service_completed_successfully
    command: mvn clean package

  tomcat:
    image: tomcat:10.1-jdk17-temurin
    ports:
      - "8080:8080"
    volumes:
      - ./target/barreiras-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      maven:
        condition: service_completed_successfully

volumes:
  mysql_data: