services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # DDL inicial
      - mysql_data:/var/lib/mysql
    healthcheck:  # 👈 Novo healthcheck
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  flyway:  # 👈 Novo serviço para migrations
    image: flyway/flyway:9
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    environment:
      FLYWAY_URL: ${DB_URL}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      flyway:
        condition: service_completed_successfully
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data: