@startuml
' https://plantuml.com/class-diagram

skinparam Dpi 100
skinparam Nodesep 80
skinparam Ranksep 80
skinparam classBackgroundColor #F9F9F9
skinparam classBorderColor #444444
skinparam classArrowColor #555555
skinparam noteBackgroundColor #FFF9C4
skinparam noteBorderColor #E0E0E0
skinparam groupInheritance 2

left to right direction

package "Usuários" {

    class Usuario {
        - id : Long
        - nome : String
        - email : String
        - dataNascimento : LocalDate
        - genero : GeneroEnum
        - senha
        - login
        + autenticar()
        + alterarSenha()
        + realizarDenuncia()
    }

     class Moderador {
        - telefone : String
        - 2Factor : boolean
        + autenticar()
    }
}

class CenarioBarreira {
    - tipo : TipoBarreiraAtitudinal
    - autor : Moderador
    - conteudo: Text
    - titulo: String
    - dataCriacao: LocalDate
    - curtidas : List<Usuario>
}

class Lei {
    - codigo : String
    - data: String
    - link : URL
    - titulo: String
    - descricao: Text
}

class Comentario {
    - dataHora : dateTime
    - conteudo : Text
    - comentarioPai : Comentario
}


class Denuncia {
    - tipo : TipoBarreiraAtitudinal
    - ambiente: TipoAmbienteEnum
    - localizacaoOcorrido : Endereco
    - severidade : Integer
    - denunciaAnonima : Boolean
    - detalhamentoOcorrido: Text
    - cenarioRelacionado : CenarioBarreira
    - denunciante : Usuario
}

class Anexo {
    - nomeArquivo : String
    - tipo : String
    - caminho : String
    - dataEnvio : LocalDateTime
}



'Herança de Pessoa
'Pessoa <|-- Usuario
Usuario <|-- Moderador
Usuario "n" -- "n" Denuncia

Comentario "1" <-- "n" Comentario : "Responde"


Moderador "1"  -- "0..*" CenarioBarreira : "Cria"

Denuncia "*" -- "1" CenarioBarreira
Denuncia "1" -- "0..*" Comentario
Lei "0..*" -- "0..*" CenarioBarreira

Denuncia *-- "0..*" Anexo
CenarioBarreira *-- "0..*" Anexo

@enduml
