@startuml
!pragma useVerticalIf on
skinparam Nodesep 150
skinparam Ranksep 150

skinparam usecase {
    BackgroundColor #F9F9F9
    BorderColor #444444
    FontSize 12
    ArrowColor #555555
    ArrowFontSize 10
}

skinparam actor {
    BackgroundColor #F9F9F9
    BorderColor #555555
    FontSize 13
}

left to right direction

' ##### ACTORES #####
actor "Usuário" as u #A2D2FF
actor "Moderador" as m #BDE0FE

' ##### AUTENTICAÇÃO #####
rectangle "Autenticação" <<boundary>> {
    (UC0: Autenticar no sistema) as uc0 #LightGray
    note right of uc0
      <b>Pré-requisito</b> para\n todas as interações
    end note
}

' ##### DENÚNCIA #####
rectangle "Denúncia" <<boundary>> {
    (UC1: Realizar Denúncia) as uc1
    (UC2: Anexar Arquivos) as uc2
    (UC3: Consultar Denúncia) as uc3
    (UC10: Vincular Cenário à Denúncia) as uc10
    (UC12: Registrar Entidade) as uc12
    (UC13: Associar Entidade à Denúncia) as uc13
}

' ##### CENÁRIOS EDUCATIVOS #####
rectangle "Cenários Educativos" <<boundary>> {
    (UC4: Consultar Cenários) as uc4
    (UC6: Curtir Cenário) as uc6
    (UC7: Criar Cenário Educativo) as uc7
    (UC8: Vincular Lei ao Cenário) as uc8
    (UC11: Comentar Cenário) as uc11
}

' ##### LEGISLAÇÃO #####
rectangle "Leis" <<boundary>> {
    (UC9: Consultar Leis Relacionadas) as uc9
}

' Usuário
u --> uc0
u --> uc3
u --> uc4
u --> uc9
uc1 --> uc2 : <<extend>>
uc0 .down.> uc1 : <<include>>
uc0 .down.> uc4 : <<include>>
uc0 .down.> uc3 : <<include>>
uc1 .down.> uc10 : <<extend>>
uc3 .down.> uc10 : <<extend>>
uc0 .down.> uc11 : <<extend>>

' Moderador
m --> uc0
m --> uc4
m --> uc3
m --> uc9
uc7 --> uc8 : <<extend>>
uc0 .down.> uc7 : <<extend>>
uc0 .down.> uc6 : <<extend>>
uc0 .down.> uc12 : <<include>>
uc0 .down.> uc13 : <<include>>

note top of u
  <b>Permissões do Usuário:</b>
  - Realizar denúncias
  - Anexar arquivos
  - Consultar denúncias próprias
  - Ver cenários educativos
  - Curtir cenários
  - Consultar leis
  - Comentar denúncias
end note

note top of m
  <b>Permissões do Moderador:</b>
  - Todas do Usuário +
  - Criar cenários
  - Vincular leis a denuncias
  - Registrar entidades
  - Associar entidade à denúncia
end note
@enduml
